### ISSUE TITLE
Possible pointercancel event issue

### ISSUE THREAD

**Issue by csuwildcat** [deltakosh/handjs#6]
I was reading through the PointerEvents spec to better understand the expected behavior when a user does something like scroll or select content during the pointer event phase; I happened upon this: http://www.w3.org/TR/pointerevents/#the-pointercancel-event. The spec specifies that `pointercancel` event should fire "if the pointer is subsequently used to manipulate the page viewport (e.g. panning or zooming)". But in my testing, the `pointercancel` event is not fired when content is scrolled then released; in Chrome this causes misfires when you release your finger from a scroll on an element because you have no way to distinguish whether the viewport was manipulated while the pointer was down.

Here's a quick demo, try scrolling the list of items and you'll notice a `pointerup` event is fired after release, but it doesn't fire a `pointercancel` beforehand to indicate a viewport manipulation occured: http://output.jsbin.com/yexuqeqoti

**Comment by SaschaNaz** [comment]
hand.js currently fires pointercancel only when the browser fires touchcancel, but Chrome has [changed its behavior](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/wHnyukcYBcA) so that it doesn't fire touchcancel in viewport manipulation anymore.

I'll investigate this more to fix this. Thank you for posting this issue!

**Comment by SaschaNaz** [comment]
https://github.com/deltakosh/handjs/commit/448bd5c1de98a1ed5add29459dd305c51fd6a241: The jsbin should now correctly show pointercancel message. Please check it out :)
